# Generated by Django 5.0.6 on 2024-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
